### ISSUE TITLE
2.4 failed to upload mainline release

### ISSUE THREAD

**Issue by torkus** [michaelnpsp/GatherMate2GasClouds#2]
hi @michaelnpsp , I noticed your 2.4 release failed to generate and upload a mainline edition to Github because of a 502 error talking to Wago: https://github.com/michaelnpsp/GatherMate2GasClouds/actions/runs/9002608908/job/24731285280

Thought you should know.

**Comment by torkus** [comment]
It looks like some of your other addons were also affected:

* KiwiFarm
* KiwiMBC
* Grid2
* CastCursor

**Comment by michaelnpsp** [comment]
I know, wago addons server was down for almost a whole day so new packages failed to upload. I will upload new packages to wago on new commits/changes.

**Comment by torkus** [comment]
brilliant, thank you very much.
